"""empty message

Revision ID: 2cef36891e87
Revises: 
Create Date: 2018-02-28 12:54:07.191166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2cef36891e87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_interface', sa.Column('methods', sa.String(length=10), nullable=False))
    op.add_column('input_interface', sa.Column('parameter_value', sa.Text(), nullable=True))
    op.drop_column('input_interface', '_methods')
    op.drop_column('input_interface', 'patameter_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_interface', sa.Column('patameter_value', mysql.TEXT(), nullable=True))
    op.add_column('input_interface', sa.Column('_methods', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('input_interface', 'parameter_value')
    op.drop_column('input_interface', 'methods')
    # ### end Alembic commands ###
