"""empty message

Revision ID: 3edef9f40297
Revises: 56d9f9bc091a
Create Date: 2018-03-01 23:33:32.733302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edef9f40297'
down_revision = '56d9f9bc091a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readcount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('counts', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readcount')
    # ### end Alembic commands ###
