"""empty message

Revision ID: 455230f87faf
Revises: a3387cbf497e
Create Date: 2018-02-28 13:58:20.473427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '455230f87faf'
down_revision = 'a3387cbf497e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_interface', sa.Column('_id', sa.Integer(), nullable=False))
    op.drop_column('input_interface', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_interface', sa.Column('id', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('input_interface', '_id')
    # ### end Alembic commands ###
