"""empty message

Revision ID: 9933d259a003
Revises: c938c22a8237
Create Date: 2018-02-28 14:17:52.148936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9933d259a003'
down_revision = 'c938c22a8237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_interface', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('input_interface', '_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_interface', sa.Column('_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('input_interface', 'id')
    # ### end Alembic commands ###
