"""empty message

Revision ID: 27b66ab815e5
Revises: 657af8efb8a4
Create Date: 2018-02-28 13:17:15.961955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27b66ab815e5'
down_revision = '657af8efb8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_interface', sa.Column('typed', sa.String(length=10), nullable=False))
    op.drop_column('input_interface', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_interface', sa.Column('type', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('input_interface', 'typed')
    # ### end Alembic commands ###
