"""empty message

Revision ID: 56d9f9bc091a
Revises: 9933d259a003
Create Date: 2018-02-28 14:36:51.895313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d9f9bc091a'
down_revision = '9933d259a003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('input_interface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('interface_name', sa.String(length=100), nullable=True),
    sa.Column('interface_url', sa.String(length=1000), nullable=False),
    sa.Column('parameter_key', sa.String(length=5000), nullable=True),
    sa.Column('parameter_value', sa.Text(), nullable=True),
    sa.Column('typed', sa.String(length=10), nullable=False),
    sa.Column('methods', sa.String(length=10), nullable=False),
    sa.Column('expected_code', sa.String(length=1000), nullable=True),
    sa.Column('sign', sa.String(length=2), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.String(length=13), nullable=True),
    sa.Column('domain', sa.String(length=500), nullable=False),
    sa.Column('have_headers', sa.String(length=2), nullable=False),
    sa.Column('author_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['front_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('input_interface')
    # ### end Alembic commands ###
