"""empty message

Revision ID: 657af8efb8a4
Revises: 2cef36891e87
Create Date: 2018-02-28 12:55:55.292449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '657af8efb8a4'
down_revision = '2cef36891e87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_interface', sa.Column('domain', sa.String(length=500), nullable=False))
    op.add_column('input_interface', sa.Column('sign', sa.String(length=2), nullable=True))
    op.add_column('input_interface', sa.Column('timestamp', sa.String(length=13), nullable=True))
    op.add_column('input_interface', sa.Column('type', sa.String(length=10), nullable=False))
    op.drop_column('input_interface', '_timestamp')
    op.drop_column('input_interface', '_domain')
    op.drop_column('input_interface', '_sign')
    op.drop_column('input_interface', '_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_interface', sa.Column('_type', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('input_interface', sa.Column('_sign', mysql.VARCHAR(length=2), nullable=True))
    op.add_column('input_interface', sa.Column('_domain', mysql.VARCHAR(length=500), nullable=False))
    op.add_column('input_interface', sa.Column('_timestamp', mysql.VARCHAR(length=13), nullable=True))
    op.drop_column('input_interface', 'type')
    op.drop_column('input_interface', 'timestamp')
    op.drop_column('input_interface', 'sign')
    op.drop_column('input_interface', 'domain')
    # ### end Alembic commands ###
