"""empty message

Revision ID: a3387cbf497e
Revises: 27b66ab815e5
Create Date: 2018-02-28 13:18:58.385411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3387cbf497e'
down_revision = '27b66ab815e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_interface', sa.Column('name', sa.String(length=20), nullable=True))
    op.drop_column('input_interface', 'app_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_interface', sa.Column('app_name', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('input_interface', 'name')
    # ### end Alembic commands ###
