"""empty message

Revision ID: c34c1d355f96
Revises: 455230f87faf
Create Date: 2018-02-28 13:58:38.868671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c34c1d355f96'
down_revision = '455230f87faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_interface', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('input_interface', '_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_interface', sa.Column('_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('input_interface', 'id')
    # ### end Alembic commands ###
