"""empty message

Revision ID: c938c22a8237
Revises: c34c1d355f96
Create Date: 2018-02-28 14:17:33.743073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c938c22a8237'
down_revision = 'c34c1d355f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_interface', sa.Column('_id', sa.Integer(), nullable=False))
    op.drop_column('input_interface', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_interface', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('input_interface', '_id')
    # ### end Alembic commands ###
